package uk.ac.aber.clg11.tsp;
/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'connorgoddard' at '03/11/15 17:44' with Gradle 2.8
 *
 * @author connorgoddard, @date 03/11/15 17:44
 */
public class TSP {
	
	public static void main(String[] args) {
        System.out.println("Hello World!");
    }
	
}
