package uk.ac.aber.clg11.tsp;

import java.util.ArrayList;
import uk.ac.aber.clg11.tsp.ga.GAChromosome;

/**
 * Provides a PERMUTATION ENCODING representation of an individual route (solution candidate) generated by the TSP-GA implementation.
 * 
 * Extends the 'GAChromosome' abstract class.
 * 
 * @author Connor Goddard (clg11@aber.ac.uk)
 *
 */
public class TSPRoute extends GAChromosome<Double, TSPLocation> {
	
	// TSPRoute provides PERMUTATION ENCODING of TSP (which is an ORDERING PROBLEM).
	// See: https://youtu.be/jnnN38tBpTo for more information.
	
	private int routeDistance = 0;

	public TSPRoute() {
		super();
	}
	
	public TSPRoute(TSPLocation[] locations) {
		super(locations);
	}
	
	public TSPRoute(ArrayList<TSPLocation> locations) {
		super(locations, false);
	}
	
	public TSPRoute(ArrayList<TSPLocation> locations, boolean shouldRandomise) {
		super(locations, shouldRandomise);
	}
	
	public ArrayList<TSPLocation> getRouteLocations() {
		return this.getGenes();
	}
	
	public TSPLocation getLocationAtPosition(int positionIndex) {
		return this.getRouteLocations().get(positionIndex);
	}
	
	public void setLocationAtPosition(int positionIndex, TSPLocation newLocation) {
		
		this.getRouteLocations().set(positionIndex, newLocation);
		
		// We need to reset the distance and fitness of the current route if we change any of the route locations.
		this.routeDistance = 0;
		super.currentFitness = 0;
		
	}

	public int getRouteDistance() {
		
		// If the route distance is yet to be calculated, then do so now.
		if (this.routeDistance <= 0) {
			this.routeDistance = calcRouteDistance();
		}
		
		return this.routeDistance;
	}
	
	/**
	 * Sums all of the distances between each of the locations along the route to calculate the total route distance.
	 * @return Integer containing the total route distance.
	 */
	private int calcRouteDistance() {
		
		int totalRouteDistance = 0;
		int routeSize = this.getRouteSize();
		ArrayList<TSPLocation> routeLocations = this.getRouteLocations();
	
		for (int i = 0; i < routeSize; i++) {
			
			TSPLocation currentLocation = routeLocations.get(i);
			
			int currentIndex = i;
			
			// We use the 'modulo' operator to make sure we return to the first location after processing the last available location.
			int nextIndex = ++currentIndex % routeSize;
			
			TSPLocation nextLocation = routeLocations.get(nextIndex);
			
			//Calculate distance between the two cities.
			totalRouteDistance += calcStraightLineDistance(currentLocation, nextLocation);
		}
		
		return totalRouteDistance;
		
	}
	
	/**
	 * Calculates the 2D straight-line distance between two TSPLocation instances.
	 * Based upon the formula available at: http://www.calculatorsoup.com/calculators/geometry-plane/distance-two-points.php for more information.
	 * @param startLocation The starting location.
	 * @param endLocation The ending location.
	 * @return The 2D straight-line distance between the coordinates represented by the start and end locations.
	 */
	private double calcStraightLineDistance(TSPLocation startLocation, TSPLocation endLocation) {
		
		// We use 'Math.abs' to prevent us from returning a negative value for the distance.
		int xDistance = Math.abs(startLocation.getxCoord() - endLocation.getxCoord());
        int yDistance = Math.abs(startLocation.getyCoord() - endLocation.getyCoord());
        
        double distance = Math.sqrt( (xDistance*xDistance) + (yDistance*yDistance) );
        
        return distance;
		
	}
	
	@Override
	public void resetFitness() {
		this.currentFitness = 0;
		this.routeDistance = 0;
	}
	
	@Override
	public Double getFitness() {
		
		if (this.currentFitness <= 0) {
			
			// As a LARGER distance represents a POORER fitness, we need to INVERT the relationship between the two.
			// See: http://www.theprojectspot.com/tutorial-post/applying-a-genetic-algorithm-to-the-travelling-salesman-problem/5 for more information.
			this.currentFitness = (1 / (double) this.getRouteDistance());
		}
		
		return this.currentFitness;
	}

	public int getRouteSize() {
		return super.getSize();
	}

	@Override
	public String toString() {
		
		String tspRouteString = "";
		
		for (int i = 0; i < this.genes.size(); i++) {
			
			tspRouteString += this.genes.get(i).toString();
			
			if (i < (this.genes.size() - 1)) {
				
				tspRouteString += " -> ";
						
			}
		}
		
		return tspRouteString;
	}
	
	

}
